version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ramirachdi/frontend:latest  # Specify the image name and tag
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm start"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ramirachdi/backend:latest  # Specify the image name and tag
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run build && npm start"
